routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'DashboardController@login')->name('login');
Route::post('authenticate', 'DashboardController@authenticate')->name('authenticate');

Route::group(['prefix' => 'portal', 'middleware' => 'auth'], function(){
	Route::get('authenticate', 'DashboardController@logout')->name('logout');

	Route::get('/', 'DashboardController@dashboard')->name('dashboard');

	Route::group(['prefix' => 'city'], function(){
		Route::get('/', 'CityController@index')->name('city');
		Route::get('/create', 'CityController@create')->name('city_create');
		Route::post('/store', 'CityController@store')->name('city_store');
		Route::get('/edit/{id}', 'CityController@edit')->name('city_edit');
		Route::post('/update/{id}', 'CityController@update')->name('city_update');

		Route::get('summary', 'CityController@summary')->name('city_summary');

		Route::group(['prefix' => 'area'], function(){
			Route::get('/', 'AreaController@index')->name('area');
			Route::get('/create', 'AreaController@create')->name('area_create');
			Route::post('/store', 'AreaController@store')->name('area_store');
			Route::get('/edit/{id}', 'AreaController@edit')->name('area_edit');
			Route::post('/update/{id}', 'AreaController@update')->name('area_update');

			Route::get('/xhr', 'AreaController@xhr')->name('area_xhr');
		});
	});

	Route::group(['prefix' => 'mangrove'], function(){
		Route::get('/', 'MangroveController@index')->name('mangrove');
		Route::get('/create', 'MangroveController@create')->name('mangrove_create');
		Route::post('/store', 'MangroveController@store')->name('mangrove_store');
		Route::get('/edit/{id}', 'MangroveController@edit')->name('mangrove_edit');
		Route::post('/update/{id}', 'MangroveController@update')->name('mangrove_update');
	});

	Route::group(['prefix' => 'inventory'], function(){
		Route::get('/', 'InventoryController@index')->name('inventory');
		Route::get('/create', 'InventoryController@create')->name('inventory_create');
		Route::post('/store', 'InventoryController@store')->name('inventory_store');
		Route::get('/edit/{id}', 'InventoryController@edit')->name('inventory_edit');
		Route::post('/update/{id}', 'InventoryController@update')->name('inventory_update');
	});

	Route::group(['prefix' => 'reports'], function(){
		Route::get('/', 'InventoryController@index')->name('reports');

		Route::group(['prefix' => 'inventory'], function(){
			Route::get('/', 'ReportsInventoryController@index')->name('report_inventory');
			Route::get('/generate-inventory', 'ReportsInventoryController@generate_inventory')->name('report_inventory_generate');

			Route::get('/summary', 'ReportsInventoryController@summary_index')->name('report_summary');
			Route::get('/generate-summary', 'ReportsInventoryController@generate_inventory_summary')->name('report_summary_generate');

			Route::get('/inventory-count', 'ReportsInventoryController@inventory_count')->name('report_inventory_summary');
			Route::get('/generate-inventory-count', 'ReportsInventoryController@generate_inventory_count')->name('report_inventory_count_generate');
		});
	});

	Route::group(['prefix' => 'user'], function(){
		Route::get('/', 'UserController@index')->name('user');
		Route::get('/create', 'UserController@create')->name('user_create');
		Route::post('/store', 'UserController@store')->name('user_store');
		Route::get('/edit/{id}', 'UserController@edit')->name('user_edit');
		Route::post('/update/{id}', 'UserController@update')->name('user_update');
		Route::get('/reset-password', 'UserController@reset_password')->name('user_reset_password');
		Route::post('/reset-password-submit', 'UserController@reset_password_submit')->name('user_reset_password_submit');

		Route::get('/generate-passwrod/{id}', 'UserController@generate_password')->name('generate_password');
	});

});

app/Inventory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    public $table = 'inventory';
    public $timestamps = true;
    public $fillable = [
    	'city_id', 'area_id', 'mangrove_id',
    	'record_date', 
        'number_of_segment', 'number_of_tree',
    	'diameter', 'height','crown', 
        'seedling', 'sapling',
    	'created_at', 'updated_at' 
    ];

    public function city()
    {
    	return $this->hasOne('App\City', 'id', 'city_id');
    }

    public function area()
    {
    	return $this->hasOne('App\Area', 'id', 'area_id');
    }

    public function mangrove()
    {
    	return $this->hasOne('App\Mangrove', 'id', 'mangrove_id');
    }

    public function setRecordDateAttribute($value)
    {
    	$this->attributes['record_date'] = date('Y-m-d', strtotime($value));
    }

    public function getMeterAttribute()
    {
        $centimeter = $this->diameter;
        $meter = $centimeter/100;

        return $meter;
    }

    public function getBasalAreaAttribute()
    {
        $centimeter = $this->diameter;
        $meter = $centimeter/100;

        return pow($meter, 2) * 0.7854;
    }

    public function getCrownCoverAttribute()
    {
        $height = $this->height;
        $crown = $this->crown;
        $crown_cover = $height * $crown;

        return $crown_cover;
    }
}

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\City;
use App\Area;
use App\Mangrove;
use App\Inventory;

class InventoryController extends Controller
{
    public function index(Request $request)
    {
        $search = '';
        
        if($request->has('search') && $request->search != '')
        {
            $search = trim($request->search);
            $rows = Inventory::with(['area', 'city', 'mangrove'])
            ->where(function($query) use ($search){
                $query->whereHas('area', function($query) use ($search){
                    $query->where('name', 'LIKE', "%$search%");
                });
            })
            ->orWhere(function($query) use ($search){
                $query->whereHas('city', function($query) use ($search){
                    $query->where('name', 'LIKE', "%$search%");
                });
            })
            ->orWhere(function($query) use ($search){
                $query->whereHas('mangrove', function($query) use ($search){
                    $query->where('name', 'LIKE', "%$search%")->orWhere('scientific_name', 'LIKE', "%$search%");
                });
            })
            ->orderBy('created_at', 'ASC')
            ->paginate(10);
            #->toSql();dd($rows);
        }
        else
        {
            $rows = Inventory::orderBy('created_at', 'ASC')->paginate(10);
        }

        $data = compact('rows', 'search');

        return view('pemo.inventory.index', $data);
    }
    
    public function create()
    {
        $action = route('inventory_store');

        $city_id = old('city_id');
        $area_id = old('area_id');
        $mangrove_id = old('mangrove_id');
        $record_date = old('record_date');
        $number_of_segment = old('number_of_segment');
        $number_of_tree = old('number_of_tree');
        $diameter = old('diameter');
        $height = old('height');
        $crown = old('crown');
        $seedling = old('seedling');
        $sapling = old('sapling');


        $cities = City::orderBy('name', 'ASC')->get();
        $areas = Area::orderBy('name', 'ASC')->get();
        $mangroves = Mangrove::orderBy('name', 'ASC')->get();

        $data = compact('action', 
            'city_id', 'area_id', 'mangrove_id',
            'record_date', 'number_of_segment', 'number_of_tree',
            'diameter', 'height','crown', 
            'seedling', 'sapling',

            'cities', 'areas', 'mangroves'
        );

        return view('pemo.inventory.form', $data);
    }
    
    public function store(Request $request)
    {
        $this->validate(
            $request, 
            [
                'city_id' => 'required|exists:city,id',
                'area_id' => 'required|exists:area,id',
                'mangrove_id' => 'required|exists:mangrove,id',

                'record_date' => 'required',
                'number_of_segment' => 'required|numeric',
                'number_of_tree' => 'required|numeric',
                'diameter' => 'required|numeric',
                'height' => 'required|numeric',
                'crown' => 'required|numeric',
                'seedling' => 'required|numeric',
                'sapling' => 'required|numeric'
            ]
        );

        $input = $request->only('city_id', 'area_id', 'mangrove_id',
            'record_date', 'number_of_segment', 'number_of_tree',
            'diameter', 'height', 'crown', 'seedling', 'sapling');

        Inventory::create($input);

        return redirect()->route('inventory_create')->with('success', 'Mangrove Data Successfully added!');
    }
    
    public function edit($id)
    {
        $action = route('inventory_update', $id);

        $row = Inventory::whereId($id)->first();
        $city_id = $row->city_id;
        $area_id = $row->area_id;
        $mangrove_id = $row->mangrove_id;
        $record_date = $row->record_date;
        $number_of_segment = $row->number_of_segment;
        $number_of_tree = $row->number_of_tree;
        $diameter = $row->diameter;
        $height = $row->height;
        $crown = $row->crown;
        $seedling = $row->seedling;
        $sapling = $row->sapling;


        $cities = City::orderBy('name', 'ASC')->get();
        $areas = Area::orderBy('name', 'ASC')->get();
        $mangroves = Mangrove::orderBy('name', 'ASC')->get();

        $data = compact('action', 
            'city_id', 'area_id', 'mangrove_id',
            'record_date', 'number_of_segment', 'number_of_tree',
            'diameter', 'height','crown', 
            'seedling', 'sapling',

            'cities', 'areas', 'mangroves'
        );

        return view('pemo.inventory.form', $data);
    }
    
    public function update($id, Request $request)
    {
        $this->validate(
            $request, 
            [
                'city_id' => 'required|exists:city,id',
                'area_id' => 'required|exists:area,id',
                'mangrove_id' => 'required|exists:mangrove,id',

                'record_date' => 'required',
                'number_of_segment' => 'required|numeric',
                'number_of_tree' => 'required|numeric',
                'diameter' => 'required|numeric',
                'height' => 'required|numeric',
                'crown' => 'required|numeric',
                'seedling' => 'required|numeric',
                'sapling' => 'required|numeric'
            ]
        );

        $input = $request->only('city_id', 'area_id', 'mangrove_id',
            'record_date', 'number_of_segment', 'number_of_tree',
            'diameter', 'height', 'crown', 'seedling', 'sapling');

        Inventory::where('id', $id)->update($input);

        return redirect()->route('inventory_create')->with('success', 'Mangrove Data Successfully added!');
    }
}

resources/views/pemo/reports/inventory/count-generate.blade.php
@extends('pemo.layouts.print')

@section('container')
@parent
	<div class="row">
		<div class="col-sm-2">Location:</div>
		<div class="col-sm-10">{{ $area->city->name }}</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Recorder:</div>
		<div class="col-sm-10">{{ Auth::user()->name }}</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Date:</div>
		<div class="col-sm-10">{{ date('F d, Y', strtotime($date_from)) . ' - ' . date('F d, Y', strtotime($date_to)) }}</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered" width="100%">
				<thead>
					<tr>
						<th>Species</th>
						<th class="text-center">Basal Area</th>
						<th class="text-center">Crown Cover</th>
					</tr>
				</thead>
				<tbody>
				@foreach($rows as $row)
				<tr>
					<td>{{ $row->name }}</td>
					<td class="text-center">{{ $row->total_basal_area($city_id, $date_from, $date_to) }}</td>
					<td class="text-center">{{ $row->total_crown_cover($city_id, $date_from, $date_to) }}</td>
				</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div>
@stop

resources/views/pemo/reports/inventory/index.blade.php
@extends('pemo.layouts.master')

@section('container')
@parent

  <section class="wrapper">

    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><i class="fa fa-text-file-o"></i> Reports</h3>
        <ol class="breadcrumb">
          <li><i class="fa fa-tree"></i><a href="{{ route('mangrove') }}">Reports</a></li>
          <li><i class="fa fa-dropbox"></i>Assessment</en>
        </ol>
      </div>
    </div>
    @include('pemo.layouts.messages')
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">Generate Inventory</header>
          <div class="panel-body">

            <form action="{{ $action }}" method="get" target="_blank" class="form-horizontal">

              <div class="form-group">
                <label class="col-sm-2 control-label" for="name">City</label>
                <div class="col-sm-3">
                  <select class="form-control" name="city_id" id="city_id">
                  <option value="">-- Select --</option>
                  @foreach($cities as $city)
                  <option value="{{ $city->id }}">{{ $city->name }}</option>
                  @endforeach
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="area_id">Area</label>
                <div class="col-sm-3">
                  <select class="form-control" name="area_id" id="area_id">
                  <option value="">-- Select --</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="beneficiary">Beneficiary</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control" name="beneficiary" value="" autofocus="">
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_from">From</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_from" value="" autofocus="" readonly="">
                </div>
              </div>


              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_to">To</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_to" value="" autofocus="" readonly="">
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  {!! csrf_field() !!}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>

            </form>

          </div>
        </section>
      </div>
    </div>
  <script type="text/javascript">
    var xhr_area_list = null;

    $(function(){
      $('#city_id').change(function(){
        area_list($(this).val(), '');
      });
    });
  </script>
@stop

resources/views/pemo/reports/inventory/inventory-count.blade.php
@extends('pemo.layouts.master')

@section('container')
@parent

  <section class="wrapper">

    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><i class="fa fa-text-file-o"></i> Reports</h3>
        <ol class="breadcrumb">
          <li><i class="fa fa-tree"></i><a href="{{ route('mangrove') }}">Reports</a></li>
          <li><i class="fa fa-dropbox"></i>Assessment</li>
        </ol>
      </div>
    </div>
    @include('pemo.layouts.messages')
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">Generate Assessment Summary</header>
          <div class="panel-body">

            <form action="{{ $action }}" method="get" target="_blank" class="form-horizontal">

              <div class="form-group">
                <label class="col-sm-2 control-label" for="name">City</label>
                <div class="col-sm-3">
                  <select class="form-control" name="city_id" id="city_id">
                  <option value="">-- Select --</option>
                  @foreach($cities as $city)
                  <option value="{{ $city->id }}">{{ $city->name }}</option>
                  @endforeach
                  </select>
                </div>
              </div>

              <!--div class="form-group">
                <label class="col-sm-2 control-label" for="area_id">Area</label>
                <div class="col-sm-3">
                  <select class="form-control" name="area_id" id="area_id">
                  <option value="">-- Select --</option>
                  </select>
                </div>
              </div-->

              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_from">From</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_from" value="" autofocus="" readonly="">
                </div>
              </div>


              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_to">To</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_to" value="" autofocus="" readonly="">
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  {!! csrf_field() !!}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>

            </form>

          </div>
        </section>
      </div>
    </div>
  <script type="text/javascript">
    var xhr_area_list = null;

    $(function(){
      $('#city_id').change(function(){
        area_list($(this).val(), '');
      });
    });
  </script>
@stop

resources/views/pemo/reports/inventory/inventory-generate.blade.php
@extends('pemo.layouts.print')

@section('container')
@parent
	<style type="text/css">
		@media print {
			#print_div {
				display: none;
			}
		}
	</style>
	<div id="print_div" class="row">
		<div class="col-sm-12">
			<button class="button" onclick="window.print()">Print</button>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Location:</div>
		<div class="col-sm-10">{{ $area->name . ', ' . $area->city->name }}</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Beneficiary:</div>
		<div class="col-sm-10">{{ $beneficiary }}</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Recorder:</div>
		<div class="col-sm-10">{{ Auth::user()->name }}</div>
	</div>
	<div class="row">
		<div class="col-sm-2">Date:</div>
		<div class="col-sm-10">{{ date('F d, Y', strtotime($date_from)) . ' - ' . date('F d, Y', strtotime($date_to)) }}</div>
	</div>
	<div class="row">
		<div class="col-sm-12">
			<table class="table table-bordered" width="100%">
				<thead>
					<tr>
						<th class="text-center">Segment</th>
						<th class="text-center">Tree</th>
						<th rowspan="2">Species</th>
						<th rowspan="2">Scientific Name</th>
						<th class="text-center">DIA</th>
						<th class="text-center">DIA</th>
						<th class="text-center">Basal Area</th>
						<th class="text-center">Total</th>
						<th class="text-center">Crown</th>
						<th class="text-center">Crown Cover</th>
						<th class="text-center" colspan="2">Regeneration</th>
						<!--th>Saplin</th-->
					</tr>
					<tr>
						<th class="text-center">No.</th>
						<th class="text-center">No.</th>
						<!--th>Species</th-->
						<!--th>Scientific Name</th-->
						<th class="text-center"><abbr title="Centimeter">cm</abbr></th>
						<th class="text-center"><abbr title="Meter">m</abbr></th>
						<th class="text-center">m2</th>
						<th class="text-center">Height (m)</th>
						<th class="text-center">DIA (m)</th>
						<th class="text-center">m2</th>
						<th class="text-center">Seedlings</th>
						<th class="text-center">Saplin</th>
					</tr>
				</thead>
				<tbody>
				@foreach($rows as $row)
				<tr>
					<td class="text-center">{{ $row->number_of_segment }}</td>
					<td class="text-center">{{ $row->number_of_tree }}</td>
					<td>{{ $row->mangrove->name }}</td>
					<td>{{ $row->mangrove->scientific_name }}</td>
					<td class="text-center">{{ $row->diameter }}</td>
					<td class="text-center">{{ $row->meter }}</td>
					<td class="text-center">{{ $row->basal_area }}</td>
					<td class="text-center">{{ $row->height }}</td>
					<td class="text-center">{{ $row->crown }}</td>
					<td class="text-center">{{ $row->crown_cover }}</td>
					<td class="text-center">{{ $row->seedling }}</td>
					<td class="text-center">{{ $row->sapling }}</td>
				</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div>
@stop

resources/views/pemo/reports/inventory/summary-index.blade.php
@extends('pemo.layouts.master')

@section('container')
@parent

  <section class="wrapper">

    <div class="row">
      <div class="col-lg-12">
        <h3 class="page-header"><i class="fa fa-text-file-o"></i> Reports</h3>
        <ol class="breadcrumb">
          <li><i class="fa fa-tree"></i><a href="{{ route('mangrove') }}">Reports</a></li>
          <li><i class="fa fa-dropbox"></i>Summary</li>
        </ol>
      </div>
    </div>
    @include('pemo.layouts.messages')
    <div class="row">
      <div class="col-lg-12">
        <section class="panel">
          <header class="panel-heading">Generate Inventory</header>
          <div class="panel-body">

            <form action="{{ $action }}" method="get" target="_blank" class="form-horizontal">

              <div class="form-group">
                <label class="col-sm-2 control-label" for="name">City</label>
                <div class="col-sm-3">
                  <select class="form-control" name="city_id" id="city_id">
                  <option value="">-- Select --</option>
                  @foreach($cities as $city)
                  <option value="{{ $city->id }}">{{ $city->name }}</option>
                  @endforeach
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="area_id">Area</label>
                <div class="col-sm-3">
                  <select class="form-control" name="area_id" id="area_id">
                  <option value="">-- Select --</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_from">From</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_from" value="" autofocus="" readonly="">
                </div>
              </div>


              <div class="form-group">
                <label class="col-sm-2 control-label" for="date_to">To</label>
                <div class="col-sm-4">
                  <input type="text" class="form-control idatepicker" name="date_to" value="" autofocus="" readonly="">
                </div>
              </div>

              <div class="form-group">
                <div class="col-lg-offset-2 col-lg-10">
                  {!! csrf_field() !!}
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </div>

            </form>

          </div>
        </section>
      </div>
    </div>
  <script type="text/javascript">
    var xhr_area_list = null;

    $(function(){
      $('#city_id').change(function(){
        area_list($(this).val(), '');
      });
    });
  </script>
@stop